### PR TITLE
Fixes a few issues in #196

### LINKED ISSUE #196: Logged in user when bypassing the purchase modal does not create a purchase record
step to create

1. enable bypass if logged in
2. purchase a free product
3. no purchase record will be created

desired functionality is that a purchase record will be created thus # 3 above is a bug.

found while testing #161

### PR DESCRIPTION
**Pull request by cklosowski**
Resolves #196

### CODE REVIEW

File: includes/download-actions.php [hunk 1]
```diff
@@ -457,13 +456,17 @@ function edd_free_downloads_process_auto_download() {
...
+			$payment->user_email  = $user->data->user_email;
 			$payment->customer_id = $customer->id;
+
 			$payment->add_download( $download_id, array( 'price' => 0 ) );
-			$payment->status = 'publish';
+			$payment->status  = 'publish';
+			$payment->gateway = 'manual';
 			$payment->save();
+
+			$payment->add_note( __( 'Purchased through EDD Free Downloads', 'edd-free-downloads' ) );
```
Comment (dannyb195) [inline includes/download-actions.php]: esc_html here

Comment (cklosowski) [reply includes/download-actions.php]: I'm actually going to hold off that, and open an issue in EDD Core. the `EDD_Payment::add_note` method should run `esc_html` so that _any_ payment note has it run.

Comment (cklosowski) [reply includes/download-actions.php]: Opened https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6082

**Comment by dannyb195** [comment]
👍 on this PR
