### PR TITLE
Fix variable priced downloads on mobile 

### LINKED ISSUE #163: File downloads fail on mobile when product has variable prices and file is assigned to price
File downloads fail on mobile when the following conditions are true:

- variable prices enabled
- file assigned to specific price
- price option is free

Disabling variable prices fixes the issue.

See https://secure.helpscout.net/conversation/374970730/60426/?folderId=180505

### PR DESCRIPTION
**Pull request by ghost1227**
Fixes #163

### CODE REVIEW

File: includes/download-actions.php [hunk 1]
```diff
@@ -321,13 +321,22 @@ function edd_free_downloads_process_auto_download() {
...
 	} else {
 		$download_id = absint( $_GET['download_id'] );
-		$price_ids   = sanitize_text_field( $_GET['price_ids'] );
+		$price_ids   = '';
+
+		if ( isset( $_GET['price_ids'] ) && $_GET['price_ids'] != '' ) {
+			$price_ids = sanitize_text_field( $_GET['price_ids'] );
+		} else {
+			if ( edd_has_variable_prices( $download_id ) ) {
+				$price_ids = '0';
```
Comment (pippinsplugins) [inline includes/download-actions.php]: This should use `edd_get_default_variable_price()` as `0` is not always a valid price ID and nor is it always the default.

**Comment by ghost1227** [comment]
@pippinsplugins Merge conflict fixed

File: includes/download-actions.php [hunk 2]
```diff
@@ -155,6 +160,29 @@ function edd_free_download_process() {
 				)
 			);
 		}
+	} elseif( isset( $price_ids ) && ! is_array( $price_ids ) ) {
+		if ( ! edd_is_free_download( $download_id, $price_ids ) ) {
+			wp_die( __( 'An internal error has occurred, please try again or contact support.', 'edd-free-downloads' ), __( 'Oops!', 'edd-free-downloads' ) );
```
Comment (pippinsplugins) [inline includes/download-actions.php]: Please make this a meaningful error message. Something like `The requested product is not free`.

Comment (ghost1227) [reply includes/download-actions.php]: That error is repeated a TON of places, usually because I deemed the user SHOULDN'T know the error. That one does make sense to change though.

Comment (pippinsplugins) [reply includes/download-actions.php]: it should be meaningful everywhere. Why should a user not know the actual reason they can't download something here?

**Comment by ghost1227** [comment]
@pippinsplugins Error text updated

File: includes/download-actions.php [hunk 3]
```diff
@@ -126,11 +126,16 @@ function edd_free_download_process() {
...
+		$price_ids = sanitize_text_field( $_GET['price_ids'] );
+	}
+
 	$download_files = array();
 
-	if ( $price_ids ) {
+	if ( isset( $price_ids ) && is_array( $price_ids ) ) {
 		foreach ( $price_ids as $cart_id => $price_id ) {
 			if ( ! edd_is_free_download( $download_id, $price_id ) ) {
 				wp_die( __( 'An internal error has occurred, please try again or contact support.', 'edd-free-downloads' ), __( 'Oops!', 'edd-free-downloads' ) );
```
Comment (pippinsplugins) [inline includes/download-actions.php]: This one too.
