### PR TITLE
Fix variable pricing free downloads on mobile #249

### LINKED ISSUE #249: No modal opens on Mobile for Variable product
If you are on mobile and click to download a variable (non single) product, the modal does not open. 

It works on single and redirects the user to a URL like this:
`https://eddtests.com/downloads/test/?edd-free-download=true&download_id=378`

But if the product has variable pricing, the modal does not work, again, only on mobile. It gives this:
`https://eddtests.mintplugins.com/downloads/free-with-variable-prices/?edd-free-download=true`

Which has no affect on the page.

### PR DESCRIPTION
**Pull request by cklosowski**
Resolves #249

Proposed changes:
1) Logs the price IDs that are $0 and selected on a variable pricing product, and appends them to the 'mobile URL'
2) Outputs `hidden` inputs on variable priced mobile view for free products.

### CODE REVIEW

File: templates/download-redirect.php [hunk 1]
```diff
@@ -156,6 +156,13 @@
 
 	<input type="hidden" name="edd_action" value="free_download_process" />
 	<input type="hidden" name="edd_free_download_id" value="<?php echo $wp_query->query_vars['download_id']; ?>" />
+
+	<?php if ( isset( $_GET['price_ids'] ) && ! empty( $price_ids = json_decode( $_GET['price_ids'] ) ) ) : ?>
```
Comment (pippinsplugins) [inline templates/download-redirect.php]: Pretty sure this triggers a fatal error on PHP 5.4 and earlier.

Comment (cklosowski) [reply templates/download-redirect.php]: Yeah it would, I'll get that fixed up.
